services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      # Basic cluster setup
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listeners and advertised listeners
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Cluster metadata storage
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # Internal topic replication (set to 1 for single-broker)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Disable telemetry to avoid unnecessary external calls
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'

    volumes:
      - ./kafka-data:/var/lib/kafka/data

  # --- Kafka UI ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  discovery-service:
    build: ./booking-system-backend/discovery-service
    container_name: discovery-service
    ports:
      - "8061:8061"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8061/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  user-service:
    build: ./booking-system-backend/user-service
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bookingdb
      - SPRING_DATASOURCE_USERNAME=booking_user
      - SPRING_DATASOURCE_PASSWORD=booking_pass
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8061/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_healthy

  booking-service:
    build: ./booking-system-backend/booking-service
    container_name: booking-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bookingdb
      - SPRING_DATASOURCE_USERNAME=booking_user
      - SPRING_DATASOURCE_PASSWORD=booking_pass
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8061/eureka/
      - USER_SERVICE_URL=http://user-service:8081
    depends_on:
      discovery-service:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  gateway-service:
    build: ./booking-system-backend/gateway-service
    container_name: gateway-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8061/eureka/
    depends_on:
      discovery-service:
        condition: service_healthy
      booking-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  # --- Frontend (React) ---
  booking-ui:
    build:
      context: ./booking-system-ui
      dockerfile: Dockerfile
    container_name: booking-ui
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  pgdata:
